spring.application.name=saas-billing-orchestrator
# Tells Spring Boot not to crash if the DB isn't available during testing/startup yet
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
