# Using variables ensures you never leak passwords on GitHub!
# These env var names match what the GitHub Actions deploy script exports from AWS SSM.
spring.datasource.billing.jdbc-url=${BILLING_DB_URL}
spring.datasource.billing.username=${BILLING_DB_USERNAME}
spring.datasource.billing.password=${BILLING_DB_PASS}

# JPA and Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Settings
server.port=8080